version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  test:
    docker:
      - image: cimg/node:15.14.0
    steps:
      - run: wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64 
      - run: mv mkcert-v1.4.3-linux-amd64 mkcert
      - run: chmod +x mkcert
      - run: sudo cp mkcert /usr/local/bin/
      - run: sudo mkcert -install
      - run: mkdir -p ~/.simulacrum/certs
      - run: cd ~/.simulacrum/certs
      - run: mkcert localhost
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm run test

workflows:
  tests:
    jobs:
      - test
