version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  test:
    docker:
      - image: cimg/node:15.14.0
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm run test

workflows:
  tests:
    jobs:
      - test
